acceptor:
  websocket: # acceptor websocket specific configuration
    remoteAddrHeaderName: "" # Use custom header name and controlled by the developers to avoid fake IP, if using proxy
  heartbeat:
    pingInterval: 5 # Time interval for actively initiating a heartbeat to the client, unit:seconds, need to be set to a positive integer greater than 0, the default value is 5
    pingMaxTimes: 2 # When N times of ping messages are continuously sent to the client, but the client did not reply to any of these messages, the server actively disconnects, which needs to be set to a positive integer greater than 0, the default value is 2
  logs:
    heartbeat:
      pingSend: true # Server send a ping message to the client
      pingSendPrintDelay: 0 # Unit:ms, Only print logs longer than x milliseconds, the default value is 0
      pingReceive: false # Receive ping message from client
      pongReceive: false # Receive pong message from client
    room:
      join: true # client join room
      leave: true # client leave room
    leaveAll: true # client leave from acceptor and leave all the rooms
initiator:
  logs:
    heartbeat: # The current heartbeat mode is: server send a ping message to the client, and the client must reply a pong message
      pingReceive: false # Receive ping message from server
      pongReceive: false # Receive pong message from server